
	<! --All other page data will be loaded into the remainder of the page-->
	<head>
			<link rel="stylesheet" type="text/css" href="./style/sidestall.css">
			<meta charset="utf-8" />
			<title>Sidestall - Video Game Recommendations</title>
			<meta name="author" content="TJ Hoplock, Mike Grinthal, Stephen Gaspar">
			<meta name="description" content="Browse and get recommendations on current and future release video games! ">
	</head>

	<div id="game" class="main">
	 <header>
	 	<h1 align="center">Pok&eacute;mon X</h1>
	 </header>

	<table border="0" width="60%" align="center" cellpadding="0" cellspacing="0">
		<tr align="center">
			<td width="20%"><img src="http://ecx.images-amazon.com/images/I/81QOS6lhb2L._SL1500_.jpg" alt="PkmnX" height="35%"/></td>
			<td width="100%" align="center">THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! THIS IS THE BEST GAME TENOUTTATEN! </td>
		</tr>
		<tr colspan="2" align="center">
			<th><a href="http://www.metacritic.com/game/3ds/pokemon-x">MetaReview 87/100 (click to view)</a></hr>
		</tr>

	</table>


	</div>